### PR TITLE
Add log subscriber

### PR DESCRIPTION
**Pull request by citrus**
Add log subscriber to prefix activerecord log messages with current database name

### CODE REVIEW

**Comment by citrus** [comment]
just rebased against your master..

**Comment by kenn** [comment]
I see several issues with this PR:

- `alias_method_chain` is deprecated in Rails 5 and that was the primary reason I had to release v2. Now we use the bare-metal `alias_method` instead (`Module#prepend` approach would create an infinite loop, so I had to resort to it). See `slavery/active_record/base.rb`
- When we patch the core library, it goes to `slavery/active_record` and directly reopen the core class and alias them, rather than `send(:include)`. If you do that in the same file (not lazy loading, etc.), there's no point in isolating them. Also see `slavery/active_record/base.rb`

Other than that, 👍

**Comment by citrus** [comment]
Thanks @kenn, I appreciate the feedback! I'll try another approach..

**Comment by kenn** [comment]
Thank you! 🎉 🎉

**Pull request merged**
